export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Golosinas super dulces',
        description: 'De menta y azucaradas',
        weight: '100 gr',
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: 'Golosinas masticables',
        description: 'Masticables de frutas',
        weight: '100 gr',
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: 'Gomitas masticables',
        description: 'Gomitas masticables frutales',
        weight: '100 gr',
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: 'Gomitas mentoladas',
        description: 'Gomitas de menta fresca',
        weight: '100 gr',
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: 'Chicles dulces',
        description: 'Chicles frutales',
        weight: '100 gr',
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: 'Chicles mentolados',
        description: 'Chicles de menta fuerte',
        weight: '100 gr',
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: 'Paletas super dulces',
        description: 'Paletas frutales',
        weight: '1 docena',
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: 'Paletas de menta',
        description: 'Paletas de menta refrescante',
        weight: '1 docena',
        price: 20,
    },
]